---
language: ruby
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - "bundle config build.nokogiri --use-system-libraries"
script: echo
notifications:
  email: false
deploy:
  provider: rubygems
  api_key:
    secure: "ew0cfiSZSfkvEFpudCUtMc8hRi2uUxkWi7B6PFH/CNFKoa9V/3Mr1qtWwhG6pl2jV/NkiVCWooGzk7Cnth9RGUm2fMCYi85zi53mrIBJoROwgbem9jUlSCc0Ir4J5Xs2p783sV8fNLBaY/cnGFF8UW8d7OKLNkf/dlQmnI7YeOg="
